import type { Metadata } from "next";
import { Providers } from "@/provider";
import "./globals.css";
import ReduxProvider from "@/store/reduxProvider";
import QueryProvider from "@/queryprovider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className="min-h-screen bg-black ">
          <ReduxProvider>
            <QueryProvider>{children}</QueryProvider>
          </ReduxProvider>
        </body>
      </Providers>
    </html>
  );
}
